name: Build Minar Ilm APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.22.0'
        
    - name: Create Flutter Project with Backup
      run: |
        echo "🔄 Creating Flutter project with proper backup..."
        
        # Project name extract karein
        PROJECT_NAME=$(grep '^name:' pubspec.yaml | awk '{print $2}')
        if [ -z "$PROJECT_NAME" ]; then
          PROJECT_NAME="minar_ilm_app"
        fi
        
        # Code backup karein
        echo "📦 Backing up your code..."
        mkdir -p /tmp/app_backup
        cp -r lib /tmp/app_backup/ 2>/dev/null || true
        cp pubspec.yaml /tmp/app_backup/ 2>/dev/null || true
        cp README.md /tmp/app_backup/ 2>/dev/null || true
        
        # Clean directory (lib ko chore kar)
        echo "🧹 Cleaning directory..."
        find . -mindepth 1 -maxdepth 1 \
          -name '.github' -prune \
          -o -name 'lib' -prune \
          -o -exec rm -rf {} +
        
        # Naya Flutter project banayein
        echo "🚀 Creating new Flutter project..."
        flutter create --org com.minarilm --project-name $PROJECT_NAME .
        
        # Apna code restore karein
        echo "📂 Restoring your code..."
        if [ -d "/tmp/app_backup/lib" ]; then
          rm -rf lib/*
          cp -r /tmp/app_backup/lib/* lib/
        fi
        if [ -f "/tmp/app_backup/pubspec.yaml" ]; then
          cp /tmp/app_backup/pubspec.yaml .
        fi
        
        echo "✅ Project structure fixed successfully!"
        
    - name: Install Dependencies
      run: flutter pub get
      
    - name: Build APK
      run: flutter build apk --release
      
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: minar-ilm-app
        path: build/app/outputs/flutter-apk/app-release.apk
        retention-days: 30
        
    - name: Show Success
      run: |
        echo "🎉 APK built successfully!"
        echo "📱 Your Minar Ilm App is ready!"
        echo "📦 Download from Artifacts section"
